// import "./any.ts";
// import "./unknown.ts";
// import "./ts-expect-error.ts";
// import "./union.ts";
// import "./never.ts";
// import "./tuple.ts";
// import "./intersection.ts";
// import "./embeded-objects-readonly.ts";
// import "./interface-advanced.ts";
import "./generic.ts";