const value = "10" / 2;
console.log(value);
const value2 = "10d" / 2;
console.log(value2);
const value3 = true - 2;
console.log(value3);
const value4 = "22" + 2;
console.log(value4);
const value5 = 4 + 5 + "44";
console.log(value5);
const value6 = 5 ** 2;
console.log(value6);
const value7 = Math.pow(4, 3);
console.log(value7);
const value8 = 7 % 2;
console.log(value8);
const value9 = 8 % 2;
console.log(value9);
const value10 = Math.floor(10.7);
console.log(value10);
const value11 = Math.ceil(10.4);
console.log(value11);
const value12 = Math.round(10.4);
console.log(value12);
const value13 = Math.round(10.6);
console.log(value13);
const minValue = Math.min(5, 3, 1, 7);
console.log(minValue);
const maxValue = Math.max(5, 3, 1, 7);
console.log(maxValue);