// import "./any.ts";
// import "./unknown.ts";
// import "./ts-expect-error.ts";
// import "./union.ts";
// import "./never.ts";
// import "./tuple.ts";
// import "./intersection.ts";
// import "./embeded-objects-readonly.ts";
// import "./interface-advanced.ts";
// import "./generic.ts";
// import "./classes.ts";
// import "./class-exercises.ts";
// import "./abstract-classes.ts";
// import "./modules/index.ts";
// import "./namespaces.ts";
import "./promises.ts";